spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pick
    username: root
    password: admin
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pick_dev
    username: root
    password: admin
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE