spring:
  datasource:
    url: jdbc:h2:~/data/eatgore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 12345678901234567890123456789012

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test

---

logging:
  config: classpath:log4j2.yml