spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?charactorEncoding=UTF-8&serverTimeZone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin